
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: assassins_courses_development
  username: postgres
  password: '@#psql.org#$%'
  #host: localhost
  #port: 5432
  #min_messages: notice
test:
  <<: *default
  database: assassins_courses_test
  username: postgres
  password: '@#psql.org#$%'

production:
  <<: *default
  database: assassins_courses_production
  username: assassins_courses
  password: <%= ENV['ASSASSINS_COURSES_DATABASE_PASSWORD'] %>
